spring:
  application:
    name: lab-4-Eureka-Server

eureka:
  server:
    enable-self-preservation: false          
    eviction-interval-timer-in-ms: 5000       
  client:
    register-with-eureka: false
    fetch-registry: false